name: bloc_clean_coding
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  http: ^1.6.0
  get_it: ^9.2.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  fluttertoast: ^9.0.0
  cached_network_image: ^3.4.1
  another_flushbar: ^1.12.32
  equatable: ^2.0.8
  flutter_secure_storage: ^10.0.0
  freezed: ^3.2.3
  google_fonts: ^8.0.2
  flutter_localization: ^0.3.3
  mocktail: ^1.0.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
